[project]
name = "lgdt_optimizer"
version = "0.1.0"
dependencies = [
"scikit-learn"
]


[project.optional-dependencies]
pydl85dep = ["cython", "cvxpy"]
experiments = ["pandas", "seaborn", "lgdt_optimizer[pydl85dep]", "pydl8.5"]

[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]
