[project]
name = "pytrees_internal"
version = "0.1.0"
dependencies = [
"scikit-learn",
]


[project.optional-dependencies]
experiments = ["pandas", "seaborn", "pydl8.5"]

[build-system]
requires = ["setuptools", "wheel", "setuptools-rust"]
