name: Rust

on:
  push:
    branches: [ "coz-profiling" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --lib
      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
            version: 0.16.0
            args: --ignore-tests
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
